title: "Lauren & Nate's Wedding"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lauren & Nate's amazing wedding. Coming August 27th, 2016
baseurl: ""
url: "http://www.monkeyandturtle.party"

# Build settings
markdown: kramdown
