title: "Lauren & Nate's Wedding"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lauren & Nate's amazing wedding. Coming August 27th, 2016
baseurl: ""
url: "http://www.monkeyandturtle.party"

# Build settings
markdown: kramdown

sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
